-- DIHASILKAN OTOMATIS oleh kliktahu/skema.py (versi skema 1). JANGAN diedit manual.
-- Untuk Bolt Database / Supabase (Postgres 15+). Jalankan di SQL editor atau sebagai migrasi.
-- RLS aktif: hanya pengguna terautentikasi & service_role yang bisa membaca/menulis (anon DITOLAK).

CREATE TABLE IF NOT EXISTS public.topik (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  nama text NOT NULL,
  pilar text NOT NULL CHECK (pilar IN ('tubuh', 'antariksa', 'bumi', 'hewan', 'teknologi', 'misteri')),
  kata_kunci jsonb NOT NULL DEFAULT '[]'::jsonb,
  aspek jsonb NOT NULL DEFAULT '[]'::jsonb,
  nama_en text,
  wiki text,
  evergreen boolean NOT NULL DEFAULT true,
  visual double precision NOT NULL DEFAULT 0.8,
  status text NOT NULL DEFAULT 'segar' CHECK (status IN ('segar', 'antre', 'dibahas', 'long', 'arsip')),
  catatan text,
  dibuat timestamptz NOT NULL DEFAULT now(),
  diubah timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.topik IS 'Registri topik/tema kanal (segar, antre, sudah dibahas).';
CREATE INDEX IF NOT EXISTS ix_topik_pilar ON public.topik (pilar);
CREATE INDEX IF NOT EXISTS ix_topik_status ON public.topik (status);
ALTER TABLE public.topik ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS kliktahu_topik_auth ON public.topik;
CREATE POLICY kliktahu_topik_auth ON public.topik FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.episode (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode text NOT NULL UNIQUE,
  format text NOT NULL CHECK (format IN ('shorts', 'long')),
  topik_id bigint REFERENCES public.topik(id) ON DELETE SET NULL,
  slug text,
  judul text,
  sudut text,
  status text NOT NULL DEFAULT 'ide' CHECK (status IN ('ide', 'riset', 'naskah', 'vo', 'render', 'rilis', 'arsip')),
  jadwal_tayang timestamptz,
  tayang timestamptz,
  youtube_id text,
  durasi_detik double precision,
  catatan text,
  dibuat timestamptz NOT NULL DEFAULT now(),
  diubah timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.episode IS 'Episode Shorts/Long (Ep50, Long03, ...) dan status produksinya.';
CREATE INDEX IF NOT EXISTS ix_episode_status ON public.episode (status);
CREATE INDEX IF NOT EXISTS ix_episode_topik_id ON public.episode (topik_id);
ALTER TABLE public.episode ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS kliktahu_episode_auth ON public.episode;
CREATE POLICY kliktahu_episode_auth ON public.episode FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.run_riset (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mulai timestamptz NOT NULL DEFAULT now(),
  selesai timestamptz,
  mode text NOT NULL CHECK (mode IN ('online', 'agen', 'uji', 'manual')),
  versi text NOT NULL,
  tanggal date NOT NULL,
  statistik jsonb NOT NULL DEFAULT '{}'::jsonb,
  catatan text
);
COMMENT ON TABLE public.run_riset IS 'Satu kali jalan mesin riset (online/agen/uji).';
CREATE INDEX IF NOT EXISTS ix_run_riset_tanggal ON public.run_riset (tanggal);
ALTER TABLE public.run_riset ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS kliktahu_run_riset_auth ON public.run_riset;
CREATE POLICY kliktahu_run_riset_auth ON public.run_riset FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.metadata (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topik_id bigint REFERENCES public.topik(id) ON DELETE SET NULL,
  episode_id bigint REFERENCES public.episode(id) ON DELETE SET NULL,
  run_id bigint REFERENCES public.run_riset(id) ON DELETE SET NULL,
  versi bigint NOT NULL DEFAULT 1,
  format text NOT NULL CHECK (format IN ('shorts', 'long')),
  kata_kunci text NOT NULL,
  judul jsonb NOT NULL,
  judul_terpilih text,
  deskripsi text NOT NULL,
  hashtag jsonb NOT NULL,
  tag jsonb NOT NULL,
  tag_karakter bigint NOT NULL,
  sumber jsonb NOT NULL DEFAULT '[]'::jsonb,
  lint jsonb NOT NULL DEFAULT '[]'::jsonb,
  lulus boolean NOT NULL DEFAULT false,
  dibuat timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.metadata IS 'Paket metadata (3 judul, deskripsi, hashtag, tag) per topik/episode, berversi.';
CREATE INDEX IF NOT EXISTS ix_metadata_topik_id ON public.metadata (topik_id);
CREATE INDEX IF NOT EXISTS ix_metadata_episode_id ON public.metadata (episode_id);
ALTER TABLE public.metadata ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS kliktahu_metadata_auth ON public.metadata;
CREATE POLICY kliktahu_metadata_auth ON public.metadata FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.snapshot_pencarian (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint REFERENCES public.run_riset(id) ON DELETE SET NULL,
  sumber text NOT NULL CHECK (sumber IN ('google_saran', 'youtube_saran', 'wikipedia', 'berita', 'gdelt', 'tren', 'youtube', 'momen', 'ilmiah', 'web', 'agen')),
  kueri text NOT NULL,
  topik_id bigint REFERENCES public.topik(id) ON DELETE SET NULL,
  diambil timestamptz NOT NULL DEFAULT now(),
  status bigint,
  durasi_ms bigint,
  dari_cache boolean NOT NULL DEFAULT false,
  jumlah bigint NOT NULL DEFAULT 0,
  data jsonb NOT NULL,
  sidik text NOT NULL
);
COMMENT ON TABLE public.snapshot_pencarian IS 'Hasil mentah-ternormalisasi tiap pencarian real-time (untuk VELOCITY & audit).';
CREATE INDEX IF NOT EXISTS ix_snapshot_pencarian_sumber_kueri ON public.snapshot_pencarian (sumber, kueri);
CREATE INDEX IF NOT EXISTS ix_snapshot_pencarian_run_id ON public.snapshot_pencarian (run_id);
CREATE INDEX IF NOT EXISTS ix_snapshot_pencarian_topik_id ON public.snapshot_pencarian (topik_id);
ALTER TABLE public.snapshot_pencarian ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS kliktahu_snapshot_pencarian_auth ON public.snapshot_pencarian;
CREATE POLICY kliktahu_snapshot_pencarian_auth ON public.snapshot_pencarian FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.skor (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint NOT NULL REFERENCES public.run_riset(id) ON DELETE CASCADE,
  topik_id bigint NOT NULL REFERENCES public.topik(id) ON DELETE CASCADE,
  peringkat bigint NOT NULL,
  status_topik text NOT NULL CHECK (status_topik IN ('segar', 'long', 'dibahas')),
  v3_skor double precision NOT NULL,
  v3_tumbuh double precision NOT NULL,
  v4_keluarga double precision,
  v5_views double precision NOT NULL,
  v6_papan double precision NOT NULL,
  v7_peluang double precision NOT NULL,
  keyakinan double precision NOT NULL,
  komponen jsonb NOT NULL,
  sinyal jsonb NOT NULL,
  UNIQUE (run_id, topik_id)
);
COMMENT ON TABLE public.skor IS 'Skor per topik per run: rumus prompt v3-v6 + v7 (peluang & keyakinan).';
CREATE INDEX IF NOT EXISTS ix_skor_topik_id ON public.skor (topik_id);
ALTER TABLE public.skor ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS kliktahu_skor_auth ON public.skor;
CREATE POLICY kliktahu_skor_auth ON public.skor FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.momen (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal date NOT NULL,
  selesai date,
  nama text NOT NULL,
  tema jsonb NOT NULL,
  jenis text NOT NULL CHECK (jenis IN ('statis', 'astro', 'live', 'agen')),
  sumber text NOT NULL,
  urgensi double precision NOT NULL DEFAULT 0,
  lokasi text,
  dibuat timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tanggal, nama)
);
COMMENT ON TABLE public.momen IS 'Kalender momen: statis (kurasi), astro (dihitung), live (umpan real-time), agen.';
CREATE INDEX IF NOT EXISTS ix_momen_tanggal ON public.momen (tanggal);
ALTER TABLE public.momen ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS kliktahu_momen_auth ON public.momen;
CREATE POLICY kliktahu_momen_auth ON public.momen FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.performa (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  episode_id bigint REFERENCES public.episode(id) ON DELETE SET NULL,
  kode text NOT NULL,
  judul text,
  tanggal date NOT NULL,
  tayangan bigint NOT NULL DEFAULT 0,
  durasi_tonton_jam double precision,
  rata_durasi_detik double precision,
  persen_ditonton double precision,
  impresi bigint,
  ctr double precision,
  subscriber bigint,
  pilar text CHECK (pilar IN ('tubuh', 'antariksa', 'bumi', 'hewan', 'teknologi', 'misteri')),
  sumber text NOT NULL CHECK (sumber IN ('studio_csv', 'performa_csv', 'manual', 'api')),
  UNIQUE (kode, tanggal)
);
COMMENT ON TABLE public.performa IS 'Performa video (impor CSV YouTube Studio / manual) -> loop bobot pilar.';
CREATE INDEX IF NOT EXISTS ix_performa_pilar ON public.performa (pilar);
ALTER TABLE public.performa ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS kliktahu_performa_auth ON public.performa;
CREATE POLICY kliktahu_performa_auth ON public.performa FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.sumber_ilmiah (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topik_id bigint NOT NULL REFERENCES public.topik(id) ON DELETE CASCADE,
  episode_id bigint REFERENCES public.episode(id) ON DELETE SET NULL,
  judul text NOT NULL,
  url text NOT NULL,
  penerbit text,
  tahun bigint,
  doi text,
  jenis text NOT NULL CHECK (jenis IN ('jurnal', 'lembaga', 'ensiklopedia', 'berita', 'lain')),
  kredibel boolean NOT NULL DEFAULT false,
  kutipan bigint,
  dibuat timestamptz NOT NULL DEFAULT now(),
  UNIQUE (topik_id, url)
);
COMMENT ON TABLE public.sumber_ilmiah IS 'Sumber kredibel per topik (jurnal, lembaga, ensiklopedia) untuk naskah & deskripsi.';
ALTER TABLE public.sumber_ilmiah ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS kliktahu_sumber_ilmiah_auth ON public.sumber_ilmiah;
CREATE POLICY kliktahu_sumber_ilmiah_auth ON public.sumber_ilmiah FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.rencana (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal date NOT NULL,
  jam text NOT NULL,
  format text NOT NULL CHECK (format IN ('shorts', 'long')),
  topik_id bigint REFERENCES public.topik(id) ON DELETE SET NULL,
  episode_kode text,
  judul_kerja text,
  alasan text,
  momen_id bigint REFERENCES public.momen(id) ON DELETE SET NULL,
  skor double precision,
  status text NOT NULL DEFAULT 'usulan' CHECK (status IN ('usulan', 'terkunci', 'selesai', 'batal')),
  dibuat timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tanggal, jam, format)
);
COMMENT ON TABLE public.rencana IS 'Kalender konten (usulan perencana / terkunci pemilik).';
CREATE INDEX IF NOT EXISTS ix_rencana_tanggal ON public.rencana (tanggal);
ALTER TABLE public.rencana ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS kliktahu_rencana_auth ON public.rencana;
CREATE POLICY kliktahu_rencana_auth ON public.rencana FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS ix_episode_cari ON public.episode USING gin (to_tsvector('simple', coalesce(kode,'') || ' ' || coalesce(judul,'') || ' ' || coalesce(sudut,'')));
